### ISSUE TITLE
REDHAWK 2.1.2: couldn't create a cpp component project with one input and output port

### ISSUE THREAD

**Issue by cindy48** [RedhawkSDR/redhawk#10]
I am using Centos6.10 and REDHAWK2.1.2. It works fine to create a cpp project without any in/out ports. However, when I add one input and one output port, I have the following error no matter what data types are assigned to the ports:

***Method '_remove_ref' could not be resolved.***

in test_cpp_base.cpp:

    test_cpp_base::~test_cpp_base()
    {
        dataFloat_in->_remove_ref();
        dataFloat_in = 0;
        dataFloat_out->_remove_ref();
        dataFloat_out = 0;
    }

It turns out that nowhere in the code system has declared / defined method "_remove_ref()".

**Comment by shmahon** [comment]
The particular method in question is native to the omniORB libraries and not REDHAWK itself.  It would appear that you do not have a valid installation of the dependencies required to develop REDHAWK components.  Please see, [External Dependencies](https://redhawksdr.github.io/2.2.1/manual/appendices/dependencies/) of the REDHAWK manual for more detail.  Some of the packages must be installed or the component's `configure` call would have failed with an error about a required package not being installed.

Can you try the following:

1.  Ensure the you have omniOrb installed.  Run the following command and make sure that you see the dependencies that are described in [External Dependencies](https://redhawksdr.github.io/2.2.1/manual/appendices/dependencies/) section of the manual (mostly the same for REDHAWK 2.2.1).
`rpm -qa | grep omni`

2.  While an RPM installation of the dependencies should have taken care of it, make sure your ldconfig path is setup properly.
`ldconfig -p | grep libomni`

3.  Ensure that you have the `omniORB-devel` rpm installed
`rpm -qa | grep omniORB-devel`

Please check back when you verified installation of all dependencies and tried to compile again.

**Comment by cindy48** [comment]
I followed the procedure in the manual "Installing REDHAWK from RPMs" closely. After performing your steps below, I got the same errors as before. However, there are no issues while I try to create a Python component project.
[owner@localhost redhawk-2.1.2-el6-x86_64]$ rpm -qa | grep omniomniORB-4.1.6-2.el6.x86_64omniORBpy-libs-3.6-3.el6.x86_64omniEvents-bootscripts-2.8.1-1.el6.x86_64libomniEvents2-2.8.1-1.el6.x86_64omniORB-utils-4.1.6-2.el6.x86_64omniORBpy-devel-3.6-3.el6.noarchomniORB-doc-4.1.6-2.el6.x86_64omniORB-devel-4.1.6-2.el6.x86_64omniEvents-utils-2.8.1-1.el6.x86_64omniEvents-server-2.8.1-1.el6.x86_64omniORB-servers-4.1.6-2.el6.x86_64python-omniORB-3.6-3.el6.noarch[owner@localhost redhawk-2.1.2-el6-x86_64]$ sudo yum install python-matplotlib \>      util-linux \>      numpy \>      omniORB \>      omniORB-devel \>      omniORB-doc \>      omniORB-servers \>      omniORB-utils \>      python-jinja2-26 \>      binutils \>      numactl \>      sqlite[sudo] password for owner: Loaded plugins: fastestmirror, refresh-packagekit, securitySetting up Install ProcessDetermining fastest mirrorsepel/metalink                                                                                                                                                                                                         |  17 kB     00:00      * base: mirror.grid.uchicago.edu * epel: mirror.grid.uchicago.edu * extras: mirror.team-cymru.com * updates: mirror.umd.edubase                                                                                                                                                                                                                  | 3.7 kB     00:00     epel                                                                                                                                                                                                                  | 3.2 kB     00:00     epel/primary                                                                                                                                                                                                          | 3.2 MB     00:01     epel                                                                                                                                                                                                                             12501/12501extras                                                                                                                                                                                                                | 3.4 kB     00:00     redhawk                                                                                                                                                                                                               | 3.6 kB     00:00 ... updates                                                                                                                                                                                                               | 3.4 kB     00:00     Package python-matplotlib-0.99.1.2-1.el6.x86_64 already installed and latest versionPackage util-linux-ng-2.17.2-12.28.el6_9.2.x86_64 already installed and latest versionPackage numpy-1.4.1-9.el6.x86_64 already installed and latest versionPackage omniORB-4.1.6-2.el6.x86_64 already installed and latest versionPackage omniORB-devel-4.1.6-2.el6.x86_64 already installed and latest versionPackage omniORB-doc-4.1.6-2.el6.x86_64 already installed and latest versionPackage omniORB-servers-4.1.6-2.el6.x86_64 already installed and latest versionPackage omniORB-utils-4.1.6-2.el6.x86_64 already installed and latest versionPackage python-jinja2-26-2.6-3.el6.noarch already installed and latest versionPackage binutils-2.20.51.0.2-5.48.el6.x86_64 already installed and latest versionPackage numactl-2.0.9-2.el6.x86_64 already installed and latest versionPackage sqlite-3.6.20-1.el6_7.2.x86_64 already installed and latest versionNothing to do[owner@localhost redhawk-2.1.2-el6-x86_64]$ ldconfig -p | grep libomni libomnithread.so.3 (libc6,x86-64) => /usr/lib64/libomnithread.so.3 libomnithread.so (libc6,x86-64) => /usr/lib64/libomnithread.so libomnisslTP4.so.1 (libc6,x86-64) => /usr/lib64/libomnisslTP4.so.1 libomnisslTP4.so (libc6,x86-64) => /usr/lib64/libomnisslTP4.so libomnijni.so.0 (libc6,x86-64) => /usr/local/redhawk/core/lib64/libomnijni.so.0 libomnijni.so (libc6,x86-64) => /usr/local/redhawk/core/lib64/libomnijni.so libomniORB4.so.1 (libc6,x86-64) => /usr/lib64/libomniORB4.so.1 libomniORB4.so (libc6,x86-64) => /usr/lib64/libomniORB4.so libomniEvents.so.2 (libc6,x86-64) => /usr/lib64/libomniEvents.so.2 libomniDynamic4.so.1 (libc6,x86-64) => /usr/lib64/libomniDynamic4.so.1 libomniDynamic4.so (libc6,x86-64) => /usr/lib64/libomniDynamic4.so libomniConnectionMgmt4.so.1 (libc6,x86-64) => /usr/lib64/libomniConnectionMgmt4.so.1 libomniConnectionMgmt4.so (libc6,x86-64) => /usr/lib64/libomniConnectionMgmt4.so libomniCodeSets4.so.1 (libc6,x86-64) => /usr/lib64/libomniCodeSets4.so.1 libomniCodeSets4.so (libc6,x86-64) => /usr/lib64/libomniCodeSets4.so[owner@localhost redhawk-2.1.2-el6-x86_64]$ rpm -qa | grep omniORB-develomniORB-devel-4.1.6-2.el6.x86_64[owner@localhost redhawk-2.1.2-el6-x86_64]$

**Comment by jirwin-geon** [comment]
In what context do you see the error message? From the build output or in the Eclipse editor?

The REDHAWK headers limit the code completions Eclipse will suggest for port classes via preprocessor macros. As a result, Eclipse is not aware of the complete class hierarchy and visually marks certain methods as "not resolved." This is a display issue and does not affect the build itself. Select "Project > Build All" or "Project > Build Project" to compile the component. If this succeeds, there are no semantic issues with your component.

When error indicators are present, trying to install the component to SDRROOT via the REDHAWK IDE will pop up a dialog that asks whether to ignore errors. You may click "Yes" or run "make install" from the console, and as long as there are no errors in the code you've added, it should compile and install.

**Comment by shmahon** [comment]
No further communication from submitter.  Issue is being closed for lack of activity.
