### ISSUE TITLE
Nodebooter does not respect the device implementation code type

### ISSUE THREAD

**Issue by btgoodwin** [RedhawkSDR/redhawk#15]
On startup, it assumes that the device code type is Executable and dispatches it as such (i.e., exec).  In the example of a shared library device, the exec will fail since it should instead be loaded like a shared library.  The error one will likely see is a kernel panic that their program counter (PC) went out of bounds since the entry point of the shared library isn't in the appropriate memory offset.

The related code can be found in the DeviceManager_impl.cpp `getCodeFilePath` method where it's checking for the local file name and entrypoint, but not the code type.

**Comment by StephenFM** [comment]
This issue was was fixed and released in REDHAWK 2.2.4.
