### ISSUE TITLE
Programmable device support of executable -type Personas

### ISSUE THREAD

**Issue by btgoodwin** [RedhawkSDR/redhawk#16]
When a Programmable device goes to load and execute a Persona that is of code type executable, the wrong entrypoint is used to create the device, which results in the `parentDevice` to not be set at the persona. This causes the Persona to be unable to make the complimentary calls to load its hardware/bitstream since it lacks a pointer to its parent.  If the Persona is created as a shared library, however, the correct entry point is used (`construct()`) and the pointer is retained in the Persona, ensuring the pattern works.

If the intended design of the Programmable and Persona device relationship is to strictly have the Persona be a shared library, then the code generators and the Programmable device logic should validate the code type as being a shared library, rejecting all other types.

**Comment by StephenFM** [comment]
This issue was addressed and released in REDHAWK 2.2.4.
