### ISSUE TITLE
IDE does not work with newer versions of Java

### ISSUE THREAD

**Issue by Payero** [RedhawkSDR/redhawk#19]
If you use any JDK newer than Java 8 the IDE does not show the Sandbox under "REDHAWK Explorer" and fails to connect to the CORBA server even though the server is running.  Once I switch to Java 8 everything works.

Java 8 will be deprecated soon so I think this will be a big problem soon

**Comment by RedhawkDeployer** [comment]
We are currently aware of the problem of running the REDHAWK IDE in Java versions greater than 8. A possible workaround for JDK 9 and 10 support for the IDE is available in https://github.com/JacORB/JacORB/issues/214 (leave out the --patch-module java.corba=jacorb-omgapi-3.9.jar line, add the rest of the -- flags to the eclipse.ini). 

Redhat is currently supporting development of OpenJDK 8 until June 2023, so there will be a supported version of JDK 8 for the lifetime of the current REDHAWK release baselines.

**Comment by kvig** [comment]
We are currently aware of the problem of running the REDHAWK IDE in Java versions greater than 8. A possible workaround for JDK 9 and 10 support for the IDE is available in https://github.com/JacORB/JacORB/issues/214 (leave out the --patch-module java.corba=jacorb-omgapi-3.9.jar line, add the rest of the -- flags to the eclipse.ini). 

Redhat is currently supporting development of OpenJDK 8 until June 2023, so there will be a supported version of JDK 8 for the lifetime of the current REDHAWK release baselines.

**Comment by kvig** [comment]
Closing the issue, there is no intended support for newer Java releases in the current long term support baselines.
