### ISSUE TITLE
Scoped lock issues

### ISSUE THREAD

**Issue by wise-sir-bedevere** [RedhawkSDR/redhawk#2]
Throughout the source tree for this project there are many uses of scoped locks of various types. In various places you see code such as :
boost::recursive_mutex::scoped_lock(load_execute_lock);
// do something with a resource

These are equivalent to:
{
    boost::recursive_mutex::scoped_lock lock(load_execute_lock);
    // lock is released here
}
// do something as a resource

Causing the lock to be released prematurely. This example is from GPP.cpp in the GPP component.

Examples can also be found in:
connectionSupport.cpp in redhawk/src/control/sdr/dommgr/connectionSupport.cpp
sourcesocket.cpp in the SourceSocket component

**Comment by shmahon** [comment]
Thank you for this feedback.  We continue to improve our static code analysis, code review and testing of the REDHAWK framework.   Since there is no discrepant behavior described by this issue, it is being closed.
