### ISSUE TITLE
SCA Specification 2.2 UML-schemes without text

### ISSUE THREAD

**Issue by se-m** [RedhawkSDR/redhawk#23]
Hi.
Sorry that I created issue here, but I was unable to find a repository for specifications.
Some of figures in "SCA Specification 2.2" pdf file having black box on place where text should be. 
![printscreen with figure 2-2](https://user-images.githubusercontent.com/642156/61280484-a082d900-a7c0-11e9-979e-4f4633025887.png)

"SCA Specification 2.0" does not have these issues.

**Comment by kvig** [comment]
We are aware of the issues with the diagrams in the PDFs; this is an artifact of the way the PDFs are generated. The 2.2.4 and future releases do not have this issue anymore.
