### ISSUE TITLE
Adding meta-redhawk-sdr layer to yocto build

### ISSUE THREAD

**Issue by Nayanacyient** [RedhawkSDR/redhawk#31]
Hi,

I have fallowed the steps for development toolkit from "BSP-Yocto-TISDK-AM57xx-PD18.1.0 Quickstart - PHYTEC Wiki ---> https://wiki.phytec.com/productinfo/phycore-am57x/bsp-yocto-tisdk-am57xx/bsp-yocto-tisdk-am57xx-pd18-2-0-quickstart/bsp-yocto-tisdk-am57xx-pd18-1-0-quickstart" and yocto build is working well.

I have target to add new meta layer "meta-redhawk-sdr" package to existing meta layers.
So, i have cloned redhawk package from 'geotech' git hub and try to build.

I added new meta layer in 'build/conf/bblayers.conf'
:${BSPDIR}/sources/meta-redhawk-sdr \

The build as completed but i didn't find any process included from new package, as per new package (attachment - README.md) process called "Domain and Device" manager task should be seen in process list.

But i didn't find those.

Can anyone help me out in this, how to bring up the process in build and should automatically boot when board is powered on.

The log after the board power on attached above.

Regards,
Nayana
[Attachments.zip](https://github.com/RedhawkSDR/redhawk/files/4070579/Attachments.zip)

**Comment by btgoodwin** [comment]
Hi @Nayanacyient,

I'm sure someone will correct me if I'm wording this incorrectly, but this organization has no ownership / responsibility over the meta-redhawk-sdr layer which is put out by GeonTech.  That said, I would be happy to help as I'm one of the authors of that layer (I see you created this issue at meta-redhawk-sdr too, so I'll cut this response off here).

**Comment by shmahon** [comment]
This issue is being closed as it is against projects that support the use of Yocto to build REDHAWK for FPGA platforms.  This project is not responsible for that work.
