### ISSUE TITLE
Python Sandbox `getStream(streamID)` bug

### ISSUE THREAD

**Issue by AndrewKWinn** [RedhawkSDR/redhawk#5]
Using *REDHAWK 2.1.2*

## BLUF
`ossie.utils.sb.DataSink.getStream` does not work due to an incorrect method call in the source code.

## Problem
 In file `/usr/local/redhawk/core/lib/python/bulkio/input_stream.py`, Line 145, the `getStreams` method of `StreamMgr` calls `getStreamID()` on each stored stream.  Assuming these are `InputStream`'s, then the correct method is `streamID()`, not `getStreamID()`

## Solution
Replace the call to `getStreamID()` with a call to `streamID()` in file `/usr/local/redhawk/core/lib/python/bulkio/input_stream.py`, Line 145.

## Minimum Working Example
```python
from ossie.utils import sb
from time import sleep

source = sb.DataSource()
sink = sb.DataSink()
source.connect(sink, providesPortName="floatIn")

sb.start()
source.push([0], streamID='test')

sleep(0.1)

s = sink.getStream('test')
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-0dbcd476ebd5> in <module>()
     11 sleep(0.1)
     12 
---> 13 s = sink.getStream('test')

/usr/local/redhawk/core/lib/python/ossie/utils/sb/io_helpers.pyc in getStream(self, streamID)
   1816 
   1817     def getStream(self, streamID):
-> 1818         return self._sink.getStream(streamID)
   1819 
   1820     def getStreams(self):

/usr/local/redhawk/core/lib/python/bulkio/input_stream.pyc in getStream(self, streamID)
    143                 return _stream
    144         for _stream in self._livingStreams:
--> 145             if self._livingStreams[_stream].getStreamID() == streamID:
    146                 return self._livingStreams[_stream]
    147         return None

AttributeError: 'InputStream' object has no attribute 'getStreamID'
```

**Comment by maxrobert** [comment]
Stream support for the sandbox's DataSource and DataSink has been superseded by StreamSink and StreamSource. These features will be available in an upcoming release of REDHAWK
