### ISSUE TITLE
redhawk-yum-3.0.0-el7-x86_64.tar.gz missing redhawk-release*.rpm

### ISSUE THREAD

**Issue by dariusjlukas** [RedhawkSDR/redhawk#50]
I'm trying to set up the yum repository for redhawk 3.0.0 however it seems to be missing the redhawk-release package (in version 2.3.0 the file was called redhawk-release-2.3.0-1.el7.noarch.rpm). I tried skipping that step, but when installing other packages I get errors about packages not being signed (I presume these are related). Is there something I'm missing, or perhaps another place to find that file?

**Comment by CumSum** [comment]
I get that error as well. The workaround I came up with was running the command: 

sudo yum --nogpgcheck groupinstall "REDHAWK Development"

**Comment by cwk29** [comment]
Thank you for pointing this out to us.

We've updated the tarball for [redhawk-yum-3.0.0-el7-x86_64.tar.gz](https://github.com/RedhawkSDR/redhawk/releases/download/3.0.0/redhawk-yum-3.0.0-el7-x86_64.tar.gz) to include the redhawk-release package, so `sudo yum install -y redhawk-release*.rpm` should now work as expected.
