### ISSUE TITLE
RH v2.3.1 - log4j,1.2.15.v201012070815 was not found.

### ISSUE THREAD

**Issue by navarrothiago** [RedhawkSDR/redhawk#53]
After updating to v2.3.1, which replaces log4j to reload4j, I start facing some problem when I try to install any plugin in the ide. The message below is shown.  

```
An error occurred while installing the items
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]org.apache.log4j 1.2.15.v201012070815, action=org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.InstallBundleAction).
The artifact file for osgi.bundle,org.apache.log4j,1.2.15.v201012070815 was not found.
```

**Comment by cdabbott** [comment]
The redhawk-ide no longer provides the `osgi.bundle,org.apache.log4j,1.2.15.v201012070815` bundle. It provides a `reload4j-1.2.19` bundle instead. [This commit](https://github.com/RedhawkSDR/gov.redhawk.core/commit/746ff03c9e8d053579012c6f5385baab8cc45c22) shows how redhawk ide plugins were updated to use the new dependency. Custom ide plugins will need to do something similar.
