### ISSUE TITLE
OSSIE

### ISSUE THREAD

**Issue by xflyor** [RedhawkSDR/redhawk#7]
I can't download OSSIE. Can you provide me with the source code of OSSIE? THANK YOU.
My email is xiafeiauv@163.com

**Comment by shmahon** [comment]
It appears that the provided download link on the OSSIE SDR page is no longer active.  While REDHAWK was originally based on OSSIE, it has long since ceased to use that code base.  As such, this request cannot be satisfied by this developer community.

Closing ticket.
